#! /usr/bin/env python

"""

Qt4 Designer File Package

This package contains all the .ui files generated by Qt 4 Designer,
as well as the python files (modules) converted from the .ui files with the
pyuic4 command.

"""