# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_launcher_item_properties.ui'
#
# Created: Fri Mar 14 16:35:45 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(438, 551)
        self.gridLayout_6 = QtGui.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.stackedWidget_2 = QtGui.QStackedWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_2.sizePolicy().hasHeightForWidth())
        self.stackedWidget_2.setSizePolicy(sizePolicy)
        self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_7 = QtGui.QLabel(self.page)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_parentPath = QtGui.QLineEdit(self.page)
        self.lineEdit_parentPath.setEnabled(True)
        self.lineEdit_parentPath.setReadOnly(True)
        self.lineEdit_parentPath.setObjectName(_fromUtf8("lineEdit_parentPath"))
        self.gridLayout_4.addWidget(self.lineEdit_parentPath, 0, 1, 1, 2)
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_dispName = QtGui.QLineEdit(self.page)
        self.lineEdit_dispName.setObjectName(_fromUtf8("lineEdit_dispName"))
        self.gridLayout_4.addWidget(self.lineEdit_dispName, 1, 1, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        spacerItem = QtGui.QSpacerItem(50, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.pushButton_icon = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_icon.sizePolicy().hasHeightForWidth())
        self.pushButton_icon.setSizePolicy(sizePolicy)
        self.pushButton_icon.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_icon.setText(_fromUtf8(""))
        self.pushButton_icon.setObjectName(_fromUtf8("pushButton_icon"))
        self.verticalLayout_9.addWidget(self.pushButton_icon)
        self.gridLayout_4.addLayout(self.verticalLayout_9, 1, 2, 2, 1)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.comboBox_itemType = QtGui.QComboBox(self.page)
        self.comboBox_itemType.setObjectName(_fromUtf8("comboBox_itemType"))
        self.comboBox_itemType.addItem(_fromUtf8(""))
        self.comboBox_itemType.addItem(_fromUtf8(""))
        self.comboBox_itemType.addItem(_fromUtf8(""))
        self.comboBox_itemType.addItem(_fromUtf8(""))
        self.comboBox_itemType.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_itemType, 2, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget_2.addWidget(self.page_2)
        self.gridLayout_6.addWidget(self.stackedWidget_2, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_page = QtGui.QWidget()
        self.page_page.setObjectName(_fromUtf8("page_page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_14 = QtGui.QLabel(self.page_page)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.plainTextEdit_page_description = QtGui.QPlainTextEdit(self.page_page)
        self.plainTextEdit_page_description.setMinimumSize(QtCore.QSize(0, 20))
        self.plainTextEdit_page_description.setObjectName(_fromUtf8("plainTextEdit_page_description"))
        self.gridLayout_3.addWidget(self.plainTextEdit_page_description, 0, 1, 2, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 410, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_page)
        self.page_info = QtGui.QWidget()
        self.page_info.setObjectName(_fromUtf8("page_info"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_info)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_13 = QtGui.QLabel(self.page_info)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.plainTextEdit_info_description = QtGui.QPlainTextEdit(self.page_info)
        self.plainTextEdit_info_description.setMinimumSize(QtCore.QSize(0, 20))
        self.plainTextEdit_info_description.setObjectName(_fromUtf8("plainTextEdit_info_description"))
        self.gridLayout_2.addWidget(self.plainTextEdit_info_description, 0, 1, 2, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 410, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_info)
        self.page_txt = QtGui.QWidget()
        self.page_txt.setObjectName(_fromUtf8("page_txt"))
        self.gridLayout_13 = QtGui.QGridLayout(self.page_txt)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_10 = QtGui.QLabel(self.page_txt)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_13.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_txt_src_filepath = QtGui.QLineEdit(self.page_txt)
        self.lineEdit_txt_src_filepath.setObjectName(_fromUtf8("lineEdit_txt_src_filepath"))
        self.gridLayout_13.addWidget(self.lineEdit_txt_src_filepath, 0, 1, 1, 1)
        self.pushButton_txt_browse = QtGui.QPushButton(self.page_txt)
        self.pushButton_txt_browse.setObjectName(_fromUtf8("pushButton_txt_browse"))
        self.gridLayout_13.addWidget(self.pushButton_txt_browse, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_txt)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_13.addWidget(self.label_11, 1, 0, 1, 1)
        self.comboBox_txt_editor = QtGui.QComboBox(self.page_txt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_txt_editor.sizePolicy().hasHeightForWidth())
        self.comboBox_txt_editor.setSizePolicy(sizePolicy)
        self.comboBox_txt_editor.setEditable(True)
        self.comboBox_txt_editor.setObjectName(_fromUtf8("comboBox_txt_editor"))
        self.comboBox_txt_editor.addItem(_fromUtf8(""))
        self.comboBox_txt_editor.addItem(_fromUtf8(""))
        self.comboBox_txt_editor.addItem(_fromUtf8(""))
        self.comboBox_txt_editor.addItem(_fromUtf8(""))
        self.comboBox_txt_editor.addItem(_fromUtf8(""))
        self.comboBox_txt_editor.addItem(_fromUtf8(""))
        self.comboBox_txt_editor.addItem(_fromUtf8(""))
        self.comboBox_txt_editor.addItem(_fromUtf8(""))
        self.comboBox_txt_editor.addItem(_fromUtf8(""))
        self.gridLayout_13.addWidget(self.comboBox_txt_editor, 1, 1, 1, 2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_12 = QtGui.QLabel(self.page_txt)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_25 = QtGui.QLabel(self.page_txt)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_2.addWidget(self.label_25)
        self.gridLayout_13.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.comboBox_txt_helpHeaderType = QtGui.QComboBox(self.page_txt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_txt_helpHeaderType.sizePolicy().hasHeightForWidth())
        self.comboBox_txt_helpHeaderType.setSizePolicy(sizePolicy)
        self.comboBox_txt_helpHeaderType.setObjectName(_fromUtf8("comboBox_txt_helpHeaderType"))
        self.comboBox_txt_helpHeaderType.addItem(_fromUtf8(""))
        self.comboBox_txt_helpHeaderType.addItem(_fromUtf8(""))
        self.comboBox_txt_helpHeaderType.addItem(_fromUtf8(""))
        self.comboBox_txt_helpHeaderType.addItem(_fromUtf8(""))
        self.gridLayout_13.addWidget(self.comboBox_txt_helpHeaderType, 2, 1, 1, 2)
        self.splitter_txt = QtGui.QSplitter(self.page_txt)
        self.splitter_txt.setOrientation(QtCore.Qt.Vertical)
        self.splitter_txt.setChildrenCollapsible(False)
        self.splitter_txt.setObjectName(_fromUtf8("splitter_txt"))
        self.layoutWidget = QtGui.QWidget(self.splitter_txt)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_11 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_30 = QtGui.QLabel(self.layoutWidget)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_6.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.layoutWidget)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_6.addWidget(self.label_31)
        self.gridLayout_11.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.plainTextEdit_txt_help = QtGui.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit_txt_help.setMinimumSize(QtCore.QSize(0, 20))
        self.plainTextEdit_txt_help.setReadOnly(True)
        self.plainTextEdit_txt_help.setObjectName(_fromUtf8("plainTextEdit_txt_help"))
        self.gridLayout_11.addWidget(self.plainTextEdit_txt_help, 0, 1, 2, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem3, 1, 0, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_txt)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_12 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_12.addWidget(self.label_8, 0, 0, 1, 1)
        self.plainTextEdit_txt_description = QtGui.QPlainTextEdit(self.layoutWidget1)
        self.plainTextEdit_txt_description.setMinimumSize(QtCore.QSize(0, 20))
        self.plainTextEdit_txt_description.setObjectName(_fromUtf8("plainTextEdit_txt_description"))
        self.gridLayout_12.addWidget(self.plainTextEdit_txt_description, 0, 1, 2, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 296, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.splitter_txt, 3, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_txt)
        self.page_pymod = QtGui.QWidget()
        self.page_pymod.setObjectName(_fromUtf8("page_pymod"))
        self.gridLayout_10 = QtGui.QGridLayout(self.page_pymod)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_16 = QtGui.QLabel(self.page_pymod)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_10.addWidget(self.label_16, 0, 0, 1, 1)
        self.comboBox_py_moduleName = QtGui.QComboBox(self.page_pymod)
        self.comboBox_py_moduleName.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_py_moduleName.sizePolicy().hasHeightForWidth())
        self.comboBox_py_moduleName.setSizePolicy(sizePolicy)
        self.comboBox_py_moduleName.setEditable(True)
        self.comboBox_py_moduleName.setObjectName(_fromUtf8("comboBox_py_moduleName"))
        self.gridLayout_10.addWidget(self.comboBox_py_moduleName, 0, 1, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.page_pymod)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_26 = QtGui.QLabel(self.page_pymod)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_3.addWidget(self.label_26)
        self.gridLayout_10.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.lineEdit_py_workingDir = QtGui.QLineEdit(self.page_pymod)
        self.lineEdit_py_workingDir.setObjectName(_fromUtf8("lineEdit_py_workingDir"))
        self.gridLayout_10.addWidget(self.lineEdit_py_workingDir, 1, 1, 1, 1)
        self.pushButton_py_browseWD = QtGui.QPushButton(self.page_pymod)
        self.pushButton_py_browseWD.setObjectName(_fromUtf8("pushButton_py_browseWD"))
        self.gridLayout_10.addWidget(self.pushButton_py_browseWD, 1, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.page_pymod)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_10.addWidget(self.label_19, 2, 0, 1, 1)
        self.lineEdit_py_args = QtGui.QLineEdit(self.page_pymod)
        self.lineEdit_py_args.setObjectName(_fromUtf8("lineEdit_py_args"))
        self.gridLayout_10.addWidget(self.lineEdit_py_args, 2, 1, 1, 2)
        self.label_17 = QtGui.QLabel(self.page_pymod)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_10.addWidget(self.label_17, 3, 0, 1, 1)
        self.comboBox_py_editor = QtGui.QComboBox(self.page_pymod)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_py_editor.sizePolicy().hasHeightForWidth())
        self.comboBox_py_editor.setSizePolicy(sizePolicy)
        self.comboBox_py_editor.setEditable(True)
        self.comboBox_py_editor.setObjectName(_fromUtf8("comboBox_py_editor"))
        self.comboBox_py_editor.addItem(_fromUtf8(""))
        self.comboBox_py_editor.addItem(_fromUtf8(""))
        self.comboBox_py_editor.addItem(_fromUtf8(""))
        self.comboBox_py_editor.addItem(_fromUtf8(""))
        self.comboBox_py_editor.addItem(_fromUtf8(""))
        self.comboBox_py_editor.addItem(_fromUtf8(""))
        self.comboBox_py_editor.addItem(_fromUtf8(""))
        self.comboBox_py_editor.addItem(_fromUtf8(""))
        self.comboBox_py_editor.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.comboBox_py_editor, 3, 1, 1, 2)
        self.splitter_py = QtGui.QSplitter(self.page_pymod)
        self.splitter_py.setOrientation(QtCore.Qt.Vertical)
        self.splitter_py.setChildrenCollapsible(False)
        self.splitter_py.setObjectName(_fromUtf8("splitter_py"))
        self.layoutWidget2 = QtGui.QWidget(self.splitter_py)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_32 = QtGui.QLabel(self.layoutWidget2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_7.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(self.layoutWidget2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_7.addWidget(self.label_33)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.plainTextEdit_py_help = QtGui.QPlainTextEdit(self.layoutWidget2)
        self.plainTextEdit_py_help.setMinimumSize(QtCore.QSize(0, 20))
        self.plainTextEdit_py_help.setReadOnly(True)
        self.plainTextEdit_py_help.setObjectName(_fromUtf8("plainTextEdit_py_help"))
        self.gridLayout_8.addWidget(self.plainTextEdit_py_help, 0, 1, 2, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 1, 0, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(self.splitter_py)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_18 = QtGui.QLabel(self.layoutWidget3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_9.addWidget(self.label_18, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 263, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem6, 1, 0, 1, 1)
        self.plainTextEdit_py_description = QtGui.QPlainTextEdit(self.layoutWidget3)
        self.plainTextEdit_py_description.setMinimumSize(QtCore.QSize(0, 20))
        self.plainTextEdit_py_description.setObjectName(_fromUtf8("plainTextEdit_py_description"))
        self.gridLayout_9.addWidget(self.plainTextEdit_py_description, 0, 1, 2, 1)
        self.gridLayout_10.addWidget(self.splitter_py, 4, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_pymod)
        self.page_exe = QtGui.QWidget()
        self.page_exe.setObjectName(_fromUtf8("page_exe"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page_exe)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_20 = QtGui.QLabel(self.page_exe)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 0, 0, 1, 1)
        self.comboBox_exe_command = QtGui.QComboBox(self.page_exe)
        self.comboBox_exe_command.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_exe_command.sizePolicy().hasHeightForWidth())
        self.comboBox_exe_command.setSizePolicy(sizePolicy)
        self.comboBox_exe_command.setEditable(True)
        self.comboBox_exe_command.setObjectName(_fromUtf8("comboBox_exe_command"))
        self.gridLayout_7.addWidget(self.comboBox_exe_command, 0, 1, 1, 2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_15 = QtGui.QLabel(self.page_exe)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout.addWidget(self.label_15)
        self.label_27 = QtGui.QLabel(self.page_exe)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout.addWidget(self.label_27)
        self.gridLayout_7.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.lineEdit_exe_workingDir = QtGui.QLineEdit(self.page_exe)
        self.lineEdit_exe_workingDir.setObjectName(_fromUtf8("lineEdit_exe_workingDir"))
        self.gridLayout_7.addWidget(self.lineEdit_exe_workingDir, 1, 1, 1, 1)
        self.pushButton_exe_browseWD = QtGui.QPushButton(self.page_exe)
        self.pushButton_exe_browseWD.setObjectName(_fromUtf8("pushButton_exe_browseWD"))
        self.gridLayout_7.addWidget(self.pushButton_exe_browseWD, 1, 2, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_24 = QtGui.QLabel(self.page_exe)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_4.addWidget(self.label_24)
        self.label_29 = QtGui.QLabel(self.page_exe)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_4.addWidget(self.label_29)
        self.gridLayout_7.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.lineEdit_exe_src_filepath = QtGui.QLineEdit(self.page_exe)
        self.lineEdit_exe_src_filepath.setObjectName(_fromUtf8("lineEdit_exe_src_filepath"))
        self.gridLayout_7.addWidget(self.lineEdit_exe_src_filepath, 2, 1, 1, 1)
        self.pushButton_exe_browse = QtGui.QPushButton(self.page_exe)
        self.pushButton_exe_browse.setObjectName(_fromUtf8("pushButton_exe_browse"))
        self.gridLayout_7.addWidget(self.pushButton_exe_browse, 2, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.page_exe)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 3, 0, 1, 1)
        self.comboBox_exe_editor = QtGui.QComboBox(self.page_exe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_exe_editor.sizePolicy().hasHeightForWidth())
        self.comboBox_exe_editor.setSizePolicy(sizePolicy)
        self.comboBox_exe_editor.setEditable(True)
        self.comboBox_exe_editor.setObjectName(_fromUtf8("comboBox_exe_editor"))
        self.comboBox_exe_editor.addItem(_fromUtf8(""))
        self.comboBox_exe_editor.addItem(_fromUtf8(""))
        self.comboBox_exe_editor.addItem(_fromUtf8(""))
        self.comboBox_exe_editor.addItem(_fromUtf8(""))
        self.comboBox_exe_editor.addItem(_fromUtf8(""))
        self.comboBox_exe_editor.addItem(_fromUtf8(""))
        self.comboBox_exe_editor.addItem(_fromUtf8(""))
        self.comboBox_exe_editor.addItem(_fromUtf8(""))
        self.comboBox_exe_editor.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_exe_editor, 3, 1, 1, 2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_23 = QtGui.QLabel(self.page_exe)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_5.addWidget(self.label_23)
        self.label_28 = QtGui.QLabel(self.page_exe)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_5.addWidget(self.label_28)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 4, 0, 1, 1)
        self.comboBox_exe_helpHeaderType = QtGui.QComboBox(self.page_exe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_exe_helpHeaderType.sizePolicy().hasHeightForWidth())
        self.comboBox_exe_helpHeaderType.setSizePolicy(sizePolicy)
        self.comboBox_exe_helpHeaderType.setObjectName(_fromUtf8("comboBox_exe_helpHeaderType"))
        self.comboBox_exe_helpHeaderType.addItem(_fromUtf8(""))
        self.comboBox_exe_helpHeaderType.addItem(_fromUtf8(""))
        self.comboBox_exe_helpHeaderType.addItem(_fromUtf8(""))
        self.comboBox_exe_helpHeaderType.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_exe_helpHeaderType, 4, 1, 1, 2)
        self.splitter_exe = QtGui.QSplitter(self.page_exe)
        self.splitter_exe.setOrientation(QtCore.Qt.Vertical)
        self.splitter_exe.setChildrenCollapsible(False)
        self.splitter_exe.setObjectName(_fromUtf8("splitter_exe"))
        self.layoutWidget4 = QtGui.QWidget(self.splitter_exe)
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_34 = QtGui.QLabel(self.layoutWidget4)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_8.addWidget(self.label_34)
        self.label_35 = QtGui.QLabel(self.layoutWidget4)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_8.addWidget(self.label_35)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.plainTextEdit_exe_help = QtGui.QPlainTextEdit(self.layoutWidget4)
        self.plainTextEdit_exe_help.setMinimumSize(QtCore.QSize(0, 20))
        self.plainTextEdit_exe_help.setReadOnly(True)
        self.plainTextEdit_exe_help.setObjectName(_fromUtf8("plainTextEdit_exe_help"))
        self.gridLayout.addWidget(self.plainTextEdit_exe_help, 0, 1, 2, 1)
        spacerItem7 = QtGui.QSpacerItem(17, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 1, 0, 1, 1)
        self.layoutWidget5 = QtGui.QWidget(self.splitter_exe)
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_22 = QtGui.QLabel(self.layoutWidget5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_5.addWidget(self.label_22, 0, 0, 1, 1)
        self.plainTextEdit_exe_description = QtGui.QPlainTextEdit(self.layoutWidget5)
        self.plainTextEdit_exe_description.setMinimumSize(QtCore.QSize(0, 20))
        self.plainTextEdit_exe_description.setObjectName(_fromUtf8("plainTextEdit_exe_description"))
        self.gridLayout_5.addWidget(self.plainTextEdit_exe_description, 0, 1, 2, 1)
        spacerItem8 = QtGui.QSpacerItem(17, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.splitter_exe, 5, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_exe)
        self.gridLayout_6.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_6.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Parent Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Item Type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_itemType.setItemText(0, QtGui.QApplication.translate("Dialog", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_itemType.setItemText(1, QtGui.QApplication.translate("Dialog", "Executable (Popen)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_itemType.setItemText(2, QtGui.QApplication.translate("Dialog", "Python Module (import executable)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_itemType.setItemText(3, QtGui.QApplication.translate("Dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_itemType.setItemText(4, QtGui.QApplication.translate("Dialog", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Filepath", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_txt_browse.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_editor.setItemText(0, QtGui.QApplication.translate("Dialog", "&default", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_editor.setItemText(1, QtGui.QApplication.translate("Dialog", "gedit", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_editor.setItemText(2, QtGui.QApplication.translate("Dialog", "&wing_new_window", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_editor.setItemText(3, QtGui.QApplication.translate("Dialog", "&wing", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_editor.setItemText(4, QtGui.QApplication.translate("Dialog", "&nano", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_editor.setItemText(5, QtGui.QApplication.translate("Dialog", "emacs", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_editor.setItemText(6, QtGui.QApplication.translate("Dialog", "&vi", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_editor.setItemText(7, QtGui.QApplication.translate("Dialog", "&matlab", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_editor.setItemText(8, QtGui.QApplication.translate("Dialog", "&matlab_no_desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Help Header", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_helpHeaderType.setItemText(0, QtGui.QApplication.translate("Dialog", "python", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_helpHeaderType.setItemText(1, QtGui.QApplication.translate("Dialog", "matlab", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_helpHeaderType.setItemText(2, QtGui.QApplication.translate("Dialog", "CSS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_txt_helpHeaderType.setItemText(3, QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Dialog", "Help in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Dialog", "Source File   ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Description  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Module Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Working", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_py_browseWD.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Arguments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_py_editor.setItemText(0, QtGui.QApplication.translate("Dialog", "&default", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_py_editor.setItemText(1, QtGui.QApplication.translate("Dialog", "&wing_new_window", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_py_editor.setItemText(2, QtGui.QApplication.translate("Dialog", "&wing", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_py_editor.setItemText(3, QtGui.QApplication.translate("Dialog", "gedit", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_py_editor.setItemText(4, QtGui.QApplication.translate("Dialog", "&nano", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_py_editor.setItemText(5, QtGui.QApplication.translate("Dialog", "emacs", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_py_editor.setItemText(6, QtGui.QApplication.translate("Dialog", "&vi", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_py_editor.setItemText(7, QtGui.QApplication.translate("Dialog", "&matlab", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_py_editor.setItemText(8, QtGui.QApplication.translate("Dialog", "&matlab_no_desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Dialog", "Help in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog", "Source File      ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Description     ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Command", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Working", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exe_browseWD.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Dialog", "Filepath", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exe_browse.setText(QtGui.QApplication.translate("Dialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_editor.setItemText(0, QtGui.QApplication.translate("Dialog", "&default", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_editor.setItemText(1, QtGui.QApplication.translate("Dialog", "gedit", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_editor.setItemText(2, QtGui.QApplication.translate("Dialog", "&wing_new_window", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_editor.setItemText(3, QtGui.QApplication.translate("Dialog", "&wing", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_editor.setItemText(4, QtGui.QApplication.translate("Dialog", "&nano", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_editor.setItemText(5, QtGui.QApplication.translate("Dialog", "emacs", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_editor.setItemText(6, QtGui.QApplication.translate("Dialog", "&vi", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_editor.setItemText(7, QtGui.QApplication.translate("Dialog", "&matlab", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_editor.setItemText(8, QtGui.QApplication.translate("Dialog", "&matlab_no_desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Help Header", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_helpHeaderType.setItemText(0, QtGui.QApplication.translate("Dialog", "python", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_helpHeaderType.setItemText(1, QtGui.QApplication.translate("Dialog", "matlab", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_helpHeaderType.setItemText(2, QtGui.QApplication.translate("Dialog", "CSS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_exe_helpHeaderType.setItemText(3, QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Dialog", "Help in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Dialog", "Source File   ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "Description  ", None, QtGui.QApplication.UnicodeUTF8))

