# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_lattice_tuner.ui'
#
# Created: Tue Nov  8 19:16:13 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1015, 766)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_switch_view = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_switch_view.setGeometry(QtCore.QRect(20, 670, 181, 41))
        self.groupBox_switch_view.setObjectName(_fromUtf8("groupBox_switch_view"))
        self.radioButton_knob_groups = QtGui.QRadioButton(self.groupBox_switch_view)
        self.radioButton_knob_groups.setGeometry(QtCore.QRect(0, 20, 101, 21))
        self.radioButton_knob_groups.setChecked(True)
        self.radioButton_knob_groups.setObjectName(_fromUtf8("radioButton_knob_groups"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_knob_groups)
        self.radioButton_knobs = QtGui.QRadioButton(self.groupBox_switch_view)
        self.radioButton_knobs.setGeometry(QtCore.QRect(110, 20, 61, 21))
        self.radioButton_knobs.setObjectName(_fromUtf8("radioButton_knobs"))
        self.buttonGroup.addButton(self.radioButton_knobs)
        self.pushButton_updatePV = QtGui.QPushButton(self.centralwidget)
        self.pushButton_updatePV.setGeometry(QtCore.QRect(250, 680, 85, 27))
        self.pushButton_updatePV.setObjectName(_fromUtf8("pushButton_updatePV"))
        self.pushButton_step_up = QtGui.QPushButton(self.centralwidget)
        self.pushButton_step_up.setGeometry(QtCore.QRect(380, 677, 41, 41))
        self.pushButton_step_up.setObjectName(_fromUtf8("pushButton_step_up"))
        self.pushButton_step_down = QtGui.QPushButton(self.centralwidget)
        self.pushButton_step_down.setGeometry(QtCore.QRect(433, 677, 41, 41))
        self.pushButton_step_down.setObjectName(_fromUtf8("pushButton_step_down"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuLoadInNewTab = QtGui.QMenu(self.menuFile)
        self.menuLoadInNewTab.setObjectName(_fromUtf8("menuLoadInNewTab"))
        self.menuLoadInCurrentTab = QtGui.QMenu(self.menuFile)
        self.menuLoadInCurrentTab.setObjectName(_fromUtf8("menuLoadInCurrentTab"))
        self.menuSave = QtGui.QMenu(self.menuFile)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewConfig = QtGui.QAction(MainWindow)
        self.actionNewConfig.setObjectName(_fromUtf8("actionNewConfig"))
        self.actionLoadConfigFileInNewTab = QtGui.QAction(MainWindow)
        self.actionLoadConfigFileInNewTab.setObjectName(_fromUtf8("actionLoadConfigFileInNewTab"))
        self.actionLoadSnapshotFileInNewTab = QtGui.QAction(MainWindow)
        self.actionLoadSnapshotFileInNewTab.setObjectName(_fromUtf8("actionLoadSnapshotFileInNewTab"))
        self.actionLoadConfigFileInCurrentTab = QtGui.QAction(MainWindow)
        self.actionLoadConfigFileInCurrentTab.setObjectName(_fromUtf8("actionLoadConfigFileInCurrentTab"))
        self.actionLoadSnapshotFileInCurrentTab = QtGui.QAction(MainWindow)
        self.actionLoadSnapshotFileInCurrentTab.setObjectName(_fromUtf8("actionLoadSnapshotFileInCurrentTab"))
        self.actionSaveConfigFile = QtGui.QAction(MainWindow)
        self.actionSaveConfigFile.setObjectName(_fromUtf8("actionSaveConfigFile"))
        self.actionSaveSnapshotFile = QtGui.QAction(MainWindow)
        self.actionSaveSnapshotFile.setObjectName(_fromUtf8("actionSaveSnapshotFile"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuLoadInNewTab.addAction(self.actionLoadConfigFileInNewTab)
        self.menuLoadInNewTab.addAction(self.actionLoadSnapshotFileInNewTab)
        self.menuLoadInCurrentTab.addAction(self.actionLoadConfigFileInCurrentTab)
        self.menuLoadInCurrentTab.addAction(self.actionLoadSnapshotFileInCurrentTab)
        self.menuSave.addAction(self.actionSaveConfigFile)
        self.menuSave.addAction(self.actionSaveSnapshotFile)
        self.menuFile.addAction(self.actionNewConfig)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuLoadInNewTab.menuAction())
        self.menuFile.addAction(self.menuLoadInCurrentTab.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lattice Tuner", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_switch_view.setTitle(QtGui.QApplication.translate("MainWindow", "View based on", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_knob_groups.setText(QtGui.QApplication.translate("MainWindow", "Knob Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_knobs.setText(QtGui.QApplication.translate("MainWindow", "Knobs", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_updatePV.setText(QtGui.QApplication.translate("MainWindow", "Update PV", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_step_up.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_step_down.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoadInNewTab.setTitle(QtGui.QApplication.translate("MainWindow", "&Load in New Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoadInCurrentTab.setTitle(QtGui.QApplication.translate("MainWindow", "Load in &Current Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewConfig.setText(QtGui.QApplication.translate("MainWindow", "&New Config...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewConfig.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadConfigFileInNewTab.setText(QtGui.QApplication.translate("MainWindow", "Config file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSnapshotFileInNewTab.setText(QtGui.QApplication.translate("MainWindow", "Snapshot file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadConfigFileInCurrentTab.setText(QtGui.QApplication.translate("MainWindow", "Config file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSnapshotFileInCurrentTab.setText(QtGui.QApplication.translate("MainWindow", "Snapshot file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveConfigFile.setText(QtGui.QApplication.translate("MainWindow", "Config to file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSnapshotFile.setText(QtGui.QApplication.translate("MainWindow", "Snapshot to file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))

