# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_lattice_tuner_for_reference.ui'
#
# Created: Tue Jan 28 16:35:46 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1015, 766)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_example = QtGui.QDockWidget(MainWindow)
        self.dockWidget_example.setObjectName(_fromUtf8("dockWidget_example"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter = QtGui.QSplitter(self.dockWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.stackedWidget = QtGui.QStackedWidget(self.splitter)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_tree = QtGui.QWidget()
        self.page_tree.setObjectName(_fromUtf8("page_tree"))
        self.gridLayout = QtGui.QGridLayout(self.page_tree)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.treeView = QtGui.QTreeView(self.page_tree)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_tree)
        self.page_table = QtGui.QWidget()
        self.page_table.setObjectName(_fromUtf8("page_table"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_table)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tableView = QtGui.QTableView(self.page_table)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_table)
        self.tabWidget_mode = QtGui.QTabWidget(self.splitter)
        self.tabWidget_mode.setObjectName(_fromUtf8("tabWidget_mode"))
        self.tab_step_mode = QtGui.QWidget()
        self.tab_step_mode.setObjectName(_fromUtf8("tab_step_mode"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_step_mode)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_tab_step_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_tab_step_2.setObjectName(_fromUtf8("horizontalLayout_tab_step_2"))
        self.pushButton_step_up = QtGui.QPushButton(self.tab_step_mode)
        self.pushButton_step_up.setObjectName(_fromUtf8("pushButton_step_up"))
        self.horizontalLayout_tab_step_2.addWidget(self.pushButton_step_up)
        self.pushButton_step_down = QtGui.QPushButton(self.tab_step_mode)
        self.pushButton_step_down.setObjectName(_fromUtf8("pushButton_step_down"))
        self.horizontalLayout_tab_step_2.addWidget(self.pushButton_step_down)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_tab_step_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_tab_step_2)
        self.horizontalLayout_tab_step_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_tab_step_1.setObjectName(_fromUtf8("horizontalLayout_tab_step_1"))
        self.pushButton_update = QtGui.QPushButton(self.tab_step_mode)
        self.pushButton_update.setObjectName(_fromUtf8("pushButton_update"))
        self.horizontalLayout_tab_step_1.addWidget(self.pushButton_update)
        self.checkBox_auto = QtGui.QCheckBox(self.tab_step_mode)
        self.checkBox_auto.setMinimumSize(QtCore.QSize(141, 0))
        self.checkBox_auto.setObjectName(_fromUtf8("checkBox_auto"))
        self.horizontalLayout_tab_step_1.addWidget(self.checkBox_auto)
        self.lineEdit_auto_update_interval = QtGui.QLineEdit(self.tab_step_mode)
        self.lineEdit_auto_update_interval.setObjectName(_fromUtf8("lineEdit_auto_update_interval"))
        self.horizontalLayout_tab_step_1.addWidget(self.lineEdit_auto_update_interval)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_tab_step_1.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_tab_step_1)
        self.tabWidget_mode.addTab(self.tab_step_mode, _fromUtf8(""))
        self.tab_ramp_mode = QtGui.QWidget()
        self.tab_ramp_mode.setObjectName(_fromUtf8("tab_ramp_mode"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_ramp_mode)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_tab_ramp_1 = QtGui.QVBoxLayout()
        self.verticalLayout_tab_ramp_1.setObjectName(_fromUtf8("verticalLayout_tab_ramp_1"))
        self.horizontalLayout_tab_ramp_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_tab_ramp_2.setObjectName(_fromUtf8("horizontalLayout_tab_ramp_2"))
        self.pushButton_copy = QtGui.QPushButton(self.tab_ramp_mode)
        self.pushButton_copy.setObjectName(_fromUtf8("pushButton_copy"))
        self.horizontalLayout_tab_ramp_2.addWidget(self.pushButton_copy)
        self.comboBox_setpoint_copy_source = QtGui.QComboBox(self.tab_ramp_mode)
        self.comboBox_setpoint_copy_source.setObjectName(_fromUtf8("comboBox_setpoint_copy_source"))
        self.comboBox_setpoint_copy_source.addItem(_fromUtf8(""))
        self.comboBox_setpoint_copy_source.addItem(_fromUtf8(""))
        self.comboBox_setpoint_copy_source.addItem(_fromUtf8(""))
        self.horizontalLayout_tab_ramp_2.addWidget(self.comboBox_setpoint_copy_source)
        self.label_tab_ramp_3 = QtGui.QLabel(self.tab_ramp_mode)
        self.label_tab_ramp_3.setObjectName(_fromUtf8("label_tab_ramp_3"))
        self.horizontalLayout_tab_ramp_2.addWidget(self.label_tab_ramp_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_tab_ramp_2.addItem(spacerItem2)
        self.verticalLayout_tab_ramp_1.addLayout(self.horizontalLayout_tab_ramp_2)
        self.horizontalLayout_tab_ramp_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_tab_ramp_1.setObjectName(_fromUtf8("horizontalLayout_tab_ramp_1"))
        self.label_tab_ramp_1 = QtGui.QLabel(self.tab_ramp_mode)
        self.label_tab_ramp_1.setObjectName(_fromUtf8("label_tab_ramp_1"))
        self.horizontalLayout_tab_ramp_1.addWidget(self.label_tab_ramp_1)
        self.lineEdit_nSteps = QtGui.QLineEdit(self.tab_ramp_mode)
        self.lineEdit_nSteps.setObjectName(_fromUtf8("lineEdit_nSteps"))
        self.horizontalLayout_tab_ramp_1.addWidget(self.lineEdit_nSteps)
        self.label_tab_ramp_2 = QtGui.QLabel(self.tab_ramp_mode)
        self.label_tab_ramp_2.setObjectName(_fromUtf8("label_tab_ramp_2"))
        self.horizontalLayout_tab_ramp_1.addWidget(self.label_tab_ramp_2)
        self.lineEdit_wait_after_each_step = QtGui.QLineEdit(self.tab_ramp_mode)
        self.lineEdit_wait_after_each_step.setObjectName(_fromUtf8("lineEdit_wait_after_each_step"))
        self.horizontalLayout_tab_ramp_1.addWidget(self.lineEdit_wait_after_each_step)
        self.verticalLayout_tab_ramp_1.addLayout(self.horizontalLayout_tab_ramp_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_tab_ramp_1)
        self.pushButton_start = QtGui.QPushButton(self.tab_ramp_mode)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.horizontalLayout_2.addWidget(self.pushButton_start)
        self.pushButton_stop = QtGui.QPushButton(self.tab_ramp_mode)
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.horizontalLayout_2.addWidget(self.pushButton_stop)
        self.pushButton_revert = QtGui.QPushButton(self.tab_ramp_mode)
        self.pushButton_revert.setObjectName(_fromUtf8("pushButton_revert"))
        self.horizontalLayout_2.addWidget(self.pushButton_revert)
        spacerItem3 = QtGui.QSpacerItem(137, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.tabWidget_mode.addTab(self.tab_ramp_mode, _fromUtf8(""))
        self.tabWidget_metadata = QtGui.QTabWidget(self.splitter)
        self.tabWidget_metadata.setObjectName(_fromUtf8("tabWidget_metadata"))
        self.tab_config_metadata = QtGui.QWidget()
        self.tab_config_metadata.setObjectName(_fromUtf8("tab_config_metadata"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_config_metadata)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_tab_conf_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_tab_conf_2.setObjectName(_fromUtf8("horizontalLayout_tab_conf_2"))
        self.label_tab_conf_2 = QtGui.QLabel(self.tab_config_metadata)
        self.label_tab_conf_2.setObjectName(_fromUtf8("label_tab_conf_2"))
        self.horizontalLayout_tab_conf_2.addWidget(self.label_tab_conf_2)
        self.lineEdit_config_username = QtGui.QLineEdit(self.tab_config_metadata)
        self.lineEdit_config_username.setObjectName(_fromUtf8("lineEdit_config_username"))
        self.horizontalLayout_tab_conf_2.addWidget(self.lineEdit_config_username)
        self.label_tab_conf_3 = QtGui.QLabel(self.tab_config_metadata)
        self.label_tab_conf_3.setObjectName(_fromUtf8("label_tab_conf_3"))
        self.horizontalLayout_tab_conf_2.addWidget(self.label_tab_conf_3)
        self.lineEdit_config_timestamp = QtGui.QLineEdit(self.tab_config_metadata)
        self.lineEdit_config_timestamp.setObjectName(_fromUtf8("lineEdit_config_timestamp"))
        self.horizontalLayout_tab_conf_2.addWidget(self.lineEdit_config_timestamp)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_tab_conf_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_tab_conf_2)
        self.horizontalLayout_tab_conf_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_tab_conf_1.setObjectName(_fromUtf8("horizontalLayout_tab_conf_1"))
        self.verticalLayout_tab_conf_1 = QtGui.QVBoxLayout()
        self.verticalLayout_tab_conf_1.setObjectName(_fromUtf8("verticalLayout_tab_conf_1"))
        self.label_tab_conf_1 = QtGui.QLabel(self.tab_config_metadata)
        self.label_tab_conf_1.setObjectName(_fromUtf8("label_tab_conf_1"))
        self.verticalLayout_tab_conf_1.addWidget(self.label_tab_conf_1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_tab_conf_1.addItem(spacerItem5)
        self.horizontalLayout_tab_conf_1.addLayout(self.verticalLayout_tab_conf_1)
        self.textEdit_config_description = QtGui.QTextEdit(self.tab_config_metadata)
        self.textEdit_config_description.setObjectName(_fromUtf8("textEdit_config_description"))
        self.horizontalLayout_tab_conf_1.addWidget(self.textEdit_config_description)
        self.verticalLayout_3.addLayout(self.horizontalLayout_tab_conf_1)
        self.tabWidget_metadata.addTab(self.tab_config_metadata, _fromUtf8(""))
        self.tab_snapshot_metadata = QtGui.QWidget()
        self.tab_snapshot_metadata.setObjectName(_fromUtf8("tab_snapshot_metadata"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_snapshot_metadata)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_tab_snap_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_tab_snap_2.setObjectName(_fromUtf8("horizontalLayout_tab_snap_2"))
        self.label_tab_snap_2 = QtGui.QLabel(self.tab_snapshot_metadata)
        self.label_tab_snap_2.setObjectName(_fromUtf8("label_tab_snap_2"))
        self.horizontalLayout_tab_snap_2.addWidget(self.label_tab_snap_2)
        self.lineEdit_snapshot_username = QtGui.QLineEdit(self.tab_snapshot_metadata)
        self.lineEdit_snapshot_username.setObjectName(_fromUtf8("lineEdit_snapshot_username"))
        self.horizontalLayout_tab_snap_2.addWidget(self.lineEdit_snapshot_username)
        self.label_tab_snap_3 = QtGui.QLabel(self.tab_snapshot_metadata)
        self.label_tab_snap_3.setObjectName(_fromUtf8("label_tab_snap_3"))
        self.horizontalLayout_tab_snap_2.addWidget(self.label_tab_snap_3)
        self.lineEdit_snapshot_timestamp = QtGui.QLineEdit(self.tab_snapshot_metadata)
        self.lineEdit_snapshot_timestamp.setObjectName(_fromUtf8("lineEdit_snapshot_timestamp"))
        self.horizontalLayout_tab_snap_2.addWidget(self.lineEdit_snapshot_timestamp)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_tab_snap_2.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_tab_snap_2)
        self.horizontalLayout_tab_snap_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_tab_snap_1.setObjectName(_fromUtf8("horizontalLayout_tab_snap_1"))
        self.verticalLayout_tab_snap_1 = QtGui.QVBoxLayout()
        self.verticalLayout_tab_snap_1.setObjectName(_fromUtf8("verticalLayout_tab_snap_1"))
        self.label_tab_snap_1 = QtGui.QLabel(self.tab_snapshot_metadata)
        self.label_tab_snap_1.setObjectName(_fromUtf8("label_tab_snap_1"))
        self.verticalLayout_tab_snap_1.addWidget(self.label_tab_snap_1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_tab_snap_1.addItem(spacerItem7)
        self.horizontalLayout_tab_snap_1.addLayout(self.verticalLayout_tab_snap_1)
        self.textEdit_snapshot_description = QtGui.QTextEdit(self.tab_snapshot_metadata)
        self.textEdit_snapshot_description.setObjectName(_fromUtf8("textEdit_snapshot_description"))
        self.horizontalLayout_tab_snap_1.addWidget(self.textEdit_snapshot_description)
        self.verticalLayout_5.addLayout(self.horizontalLayout_tab_snap_1)
        self.tabWidget_metadata.addTab(self.tab_snapshot_metadata, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.dockWidget_example.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_example)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuLoad = QtGui.QMenu(self.menuFile)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        MainWindow.setMenuBar(self.menubar)
        self.actionNewConfig = QtGui.QAction(MainWindow)
        self.actionNewConfig.setObjectName(_fromUtf8("actionNewConfig"))
        self.actionLoadConfigFileInNewTab = QtGui.QAction(MainWindow)
        self.actionLoadConfigFileInNewTab.setObjectName(_fromUtf8("actionLoadConfigFileInNewTab"))
        self.actionLoadSnapshotFileInNewTab = QtGui.QAction(MainWindow)
        self.actionLoadSnapshotFileInNewTab.setObjectName(_fromUtf8("actionLoadSnapshotFileInNewTab"))
        self.actionLoadConfigFileInCurrentTab = QtGui.QAction(MainWindow)
        self.actionLoadConfigFileInCurrentTab.setObjectName(_fromUtf8("actionLoadConfigFileInCurrentTab"))
        self.actionLoadSnapshotFileInCurrentTab = QtGui.QAction(MainWindow)
        self.actionLoadSnapshotFileInCurrentTab.setObjectName(_fromUtf8("actionLoadSnapshotFileInCurrentTab"))
        self.actionSaveConfigFile = QtGui.QAction(MainWindow)
        self.actionSaveConfigFile.setObjectName(_fromUtf8("actionSaveConfigFile"))
        self.actionSaveSnapshotFile = QtGui.QAction(MainWindow)
        self.actionSaveSnapshotFile.setObjectName(_fromUtf8("actionSaveSnapshotFile"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionLoadConfig = QtGui.QAction(MainWindow)
        self.actionLoadConfig.setObjectName(_fromUtf8("actionLoadConfig"))
        self.actionLoadSnapshot = QtGui.QAction(MainWindow)
        self.actionLoadSnapshot.setObjectName(_fromUtf8("actionLoadSnapshot"))
        self.actionViewGroupeBased = QtGui.QAction(MainWindow)
        self.actionViewGroupeBased.setObjectName(_fromUtf8("actionViewGroupeBased"))
        self.actionViewChannelBased = QtGui.QAction(MainWindow)
        self.actionViewChannelBased.setObjectName(_fromUtf8("actionViewChannelBased"))
        self.actionConfig_Metadata = QtGui.QAction(MainWindow)
        self.actionConfig_Metadata.setObjectName(_fromUtf8("actionConfig_Metadata"))
        self.actionSnapshot_Metadata = QtGui.QAction(MainWindow)
        self.actionSnapshot_Metadata.setObjectName(_fromUtf8("actionSnapshot_Metadata"))
        self.actionDefault_config_columns = QtGui.QAction(MainWindow)
        self.actionDefault_config_columns.setObjectName(_fromUtf8("actionDefault_config_columns"))
        self.actionDefault_snapshot_columns = QtGui.QAction(MainWindow)
        self.actionDefault_snapshot_columns.setObjectName(_fromUtf8("actionDefault_snapshot_columns"))
        self.actionUser_defined_config_columns = QtGui.QAction(MainWindow)
        self.actionUser_defined_config_columns.setObjectName(_fromUtf8("actionUser_defined_config_columns"))
        self.actionUser_defined_snapshot_columns = QtGui.QAction(MainWindow)
        self.actionUser_defined_snapshot_columns.setObjectName(_fromUtf8("actionUser_defined_snapshot_columns"))
        self.menuLoad.addAction(self.actionLoadConfig)
        self.menuLoad.addAction(self.actionLoadSnapshot)
        self.menuFile.addAction(self.actionNewConfig)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_mode.setCurrentIndex(1)
        self.tabWidget_metadata.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "AP Tinker", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_step_up.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_step_down.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_update.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_auto.setText(QtGui.QApplication.translate("MainWindow", "Auto: Interval [s]", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_mode.setTabText(self.tabWidget_mode.indexOf(self.tab_step_mode), QtGui.QApplication.translate("MainWindow", "Step Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_copy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_setpoint_copy_source.setItemText(0, QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_setpoint_copy_source.setItemText(1, QtGui.QApplication.translate("MainWindow", "Initial", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_setpoint_copy_source.setItemText(2, QtGui.QApplication.translate("MainWindow", "Snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab_ramp_3.setText(QtGui.QApplication.translate("MainWindow", "setpoints into target setpoints", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab_ramp_1.setText(QtGui.QApplication.translate("MainWindow", "Number of Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab_ramp_2.setText(QtGui.QApplication.translate("MainWindow", "Wait after Each Step [s]:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_revert.setText(QtGui.QApplication.translate("MainWindow", "Revert", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_mode.setTabText(self.tabWidget_mode.indexOf(self.tab_ramp_mode), QtGui.QApplication.translate("MainWindow", "Ramp Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab_conf_2.setText(QtGui.QApplication.translate("MainWindow", "Created by", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab_conf_3.setText(QtGui.QApplication.translate("MainWindow", "Created on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab_conf_1.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_metadata.setTabText(self.tabWidget_metadata.indexOf(self.tab_config_metadata), QtGui.QApplication.translate("MainWindow", "Config Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab_snap_2.setText(QtGui.QApplication.translate("MainWindow", "Created by", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab_snap_3.setText(QtGui.QApplication.translate("MainWindow", "Created on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_tab_snap_1.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_metadata.setTabText(self.tabWidget_metadata.indexOf(self.tab_snapshot_metadata), QtGui.QApplication.translate("MainWindow", "Snapshot Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad.setTitle(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindow.setTitle(QtGui.QApplication.translate("MainWindow", "Window", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewConfig.setText(QtGui.QApplication.translate("MainWindow", "&New Config...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewConfig.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadConfigFileInNewTab.setText(QtGui.QApplication.translate("MainWindow", "Config file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSnapshotFileInNewTab.setText(QtGui.QApplication.translate("MainWindow", "Snapshot file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadConfigFileInCurrentTab.setText(QtGui.QApplication.translate("MainWindow", "Config file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSnapshotFileInCurrentTab.setText(QtGui.QApplication.translate("MainWindow", "Snapshot file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveConfigFile.setText(QtGui.QApplication.translate("MainWindow", "Config to file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSnapshotFile.setText(QtGui.QApplication.translate("MainWindow", "Snapshot to file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "Load Snapshot File...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadConfig.setText(QtGui.QApplication.translate("MainWindow", "config...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSnapshot.setText(QtGui.QApplication.translate("MainWindow", "snapshot...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewGroupeBased.setText(QtGui.QApplication.translate("MainWindow", "&Groupe-based", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewChannelBased.setText(QtGui.QApplication.translate("MainWindow", "&Channel-based", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfig_Metadata.setText(QtGui.QApplication.translate("MainWindow", "Config Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSnapshot_Metadata.setText(QtGui.QApplication.translate("MainWindow", "Snapshot Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefault_config_columns.setText(QtGui.QApplication.translate("MainWindow", "Default config columns", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefault_snapshot_columns.setText(QtGui.QApplication.translate("MainWindow", "Default snapshot columns", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUser_defined_config_columns.setText(QtGui.QApplication.translate("MainWindow", "User-defined config columns", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUser_defined_snapshot_columns.setText(QtGui.QApplication.translate("MainWindow", "User-defined snapshot columns", None, QtGui.QApplication.UnicodeUTF8))

