# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_preferencesDialogForConfigSetup.ui'
#
# Created: Mon Nov  7 14:15:05 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(677, 549)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_NotSelected = QtGui.QLabel(Dialog)
        self.label_NotSelected.setObjectName(_fromUtf8("label_NotSelected"))
        self.verticalLayout.addWidget(self.label_NotSelected)
        self.listWidget_NotSelected = QtGui.QListWidget(Dialog)
        self.listWidget_NotSelected.setObjectName(_fromUtf8("listWidget_NotSelected"))
        self.verticalLayout.addWidget(self.listWidget_NotSelected)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 178, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_right_arrow = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_right_arrow.sizePolicy().hasHeightForWidth())
        self.pushButton_right_arrow.setSizePolicy(sizePolicy)
        self.pushButton_right_arrow.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_right_arrow.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_right_arrow.setObjectName(_fromUtf8("pushButton_right_arrow"))
        self.verticalLayout_3.addWidget(self.pushButton_right_arrow)
        spacerItem1 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pushButton_left_arrow = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_left_arrow.sizePolicy().hasHeightForWidth())
        self.pushButton_left_arrow.setSizePolicy(sizePolicy)
        self.pushButton_left_arrow.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_left_arrow.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_left_arrow.setObjectName(_fromUtf8("pushButton_left_arrow"))
        self.verticalLayout_3.addWidget(self.pushButton_left_arrow)
        spacerItem2 = QtGui.QSpacerItem(20, 178, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_Selected = QtGui.QLabel(Dialog)
        self.label_Selected.setObjectName(_fromUtf8("label_Selected"))
        self.verticalLayout_2.addWidget(self.label_Selected)
        self.listWidget_Selected = QtGui.QListWidget(Dialog)
        self.listWidget_Selected.setObjectName(_fromUtf8("listWidget_Selected"))
        self.verticalLayout_2.addWidget(self.listWidget_Selected)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 3, 1, 2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(20, 178, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.pushButton_up_arrow = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_up_arrow.sizePolicy().hasHeightForWidth())
        self.pushButton_up_arrow.setSizePolicy(sizePolicy)
        self.pushButton_up_arrow.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_up_arrow.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_up_arrow.setObjectName(_fromUtf8("pushButton_up_arrow"))
        self.verticalLayout_4.addWidget(self.pushButton_up_arrow)
        spacerItem4 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.pushButton_down_arrow = QtGui.QPushButton(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_down_arrow.sizePolicy().hasHeightForWidth())
        self.pushButton_down_arrow.setSizePolicy(sizePolicy)
        self.pushButton_down_arrow.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_down_arrow.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_down_arrow.setObjectName(_fromUtf8("pushButton_down_arrow"))
        self.verticalLayout_4.addWidget(self.pushButton_down_arrow)
        spacerItem5 = QtGui.QSpacerItem(20, 178, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 5, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_loadFromFile = QtGui.QPushButton(Dialog)
        self.pushButton_loadFromFile.setObjectName(_fromUtf8("pushButton_loadFromFile"))
        self.horizontalLayout.addWidget(self.pushButton_loadFromFile)
        self.pushButton_saveToFile = QtGui.QPushButton(Dialog)
        self.pushButton_saveToFile.setObjectName(_fromUtf8("pushButton_saveToFile"))
        self.horizontalLayout.addWidget(self.pushButton_saveToFile)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(258, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 1, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 4, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Item List Selection Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_NotSelected.setText(QtGui.QApplication.translate("Dialog", "NOT Visible Column Names:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_right_arrow.setText(QtGui.QApplication.translate("Dialog", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_left_arrow.setText(QtGui.QApplication.translate("Dialog", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Selected.setText(QtGui.QApplication.translate("Dialog", "Visible Column Names:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_up_arrow.setText(QtGui.QApplication.translate("Dialog", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_down_arrow.setText(QtGui.QApplication.translate("Dialog", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_loadFromFile.setText(QtGui.QApplication.translate("Dialog", "Load from file..", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_saveToFile.setText(QtGui.QApplication.translate("Dialog", "Save to file...", None, QtGui.QApplication.UnicodeUTF8))

