# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tunerConfigSetupDialog.ui'
#
# Created: Fri Jan 17 13:56:17 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(843, 605)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter_top_bottom = QtGui.QSplitter(Dialog)
        self.splitter_top_bottom.setOrientation(QtCore.Qt.Vertical)
        self.splitter_top_bottom.setObjectName(_fromUtf8("splitter_top_bottom"))
        self.stackedWidget = QtGui.QStackedWidget(self.splitter_top_bottom)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_tree = QtGui.QWidget()
        self.page_tree.setObjectName(_fromUtf8("page_tree"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_tree)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.treeView = QtGui.QTreeView(self.page_tree)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.gridLayout_2.addWidget(self.treeView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_tree)
        self.page_table = QtGui.QWidget()
        self.page_table.setObjectName(_fromUtf8("page_table"))
        self.gridLayout = QtGui.QGridLayout(self.page_table)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableView = QtGui.QTableView(self.page_table)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_table)
        self.splitter_left_right = QtGui.QSplitter(self.splitter_top_bottom)
        self.splitter_left_right.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_left_right.setObjectName(_fromUtf8("splitter_left_right"))
        self.layoutWidget = QtGui.QWidget(self.splitter_left_right)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.comboBox_view = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_view.setObjectName(_fromUtf8("comboBox_view"))
        self.comboBox_view.addItem(_fromUtf8(""))
        self.comboBox_view.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_view)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_import = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_import.setObjectName(_fromUtf8("pushButton_import"))
        self.verticalLayout_4.addWidget(self.pushButton_import)
        self.pushButton_export = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_export.setObjectName(_fromUtf8("pushButton_export"))
        self.verticalLayout_4.addWidget(self.pushButton_export)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox_import = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_import.setObjectName(_fromUtf8("comboBox_import"))
        self.comboBox_import.addItem(_fromUtf8(""))
        self.comboBox_import.addItem(_fromUtf8(""))
        self.comboBox_import.addItem(_fromUtf8(""))
        self.comboBox_import.addItem(_fromUtf8(""))
        self.comboBox_import.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_import)
        self.comboBox_export = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_export.setObjectName(_fromUtf8("comboBox_export"))
        self.comboBox_export.addItem(_fromUtf8(""))
        self.comboBox_export.addItem(_fromUtf8(""))
        self.comboBox_export.addItem(_fromUtf8(""))
        self.comboBox_export.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_export)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_left_right)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_config_name = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_config_name.setObjectName(_fromUtf8("lineEdit_config_name"))
        self.horizontalLayout.addWidget(self.lineEdit_config_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget1)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addWidget(self.splitter_top_bottom, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_preferences = QtGui.QPushButton(Dialog)
        self.pushButton_preferences.setObjectName(_fromUtf8("pushButton_preferences"))
        self.horizontalLayout_2.addWidget(self.pushButton_preferences)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Setup Dialog for Tuner Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_view.setItemText(0, QtGui.QApplication.translate("Dialog", "Group-based View", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_view.setItemText(1, QtGui.QApplication.translate("Dialog", "Channel-based View", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_import.setText(QtGui.QApplication.translate("Dialog", "Import from", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_export.setText(QtGui.QApplication.translate("Dialog", "Export to", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_import.setItemText(0, QtGui.QApplication.translate("Dialog", "Channel Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_import.setItemText(1, QtGui.QApplication.translate("Dialog", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_import.setItemText(2, QtGui.QApplication.translate("Dialog", "HDF5 File", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_import.setItemText(3, QtGui.QApplication.translate("Dialog", "JSON File", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_import.setItemText(4, QtGui.QApplication.translate("Dialog", "Text File", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_export.setItemText(0, QtGui.QApplication.translate("Dialog", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_export.setItemText(1, QtGui.QApplication.translate("Dialog", "HDF5 File", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_export.setItemText(2, QtGui.QApplication.translate("Dialog", "JSON File", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_export.setItemText(3, QtGui.QApplication.translate("Dialog", "Text File", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Config Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_preferences.setText(QtGui.QApplication.translate("Dialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))

