# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tunerConfigSetupDialog.ui'
#
# Created: Wed Nov 28 12:11:21 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(843, 605)
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter_top_bottom = QtGui.QSplitter(Dialog)
        self.splitter_top_bottom.setOrientation(QtCore.Qt.Vertical)
        self.splitter_top_bottom.setObjectName("splitter_top_bottom")
        self.stackedWidget = QtGui.QStackedWidget(self.splitter_top_bottom)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_tree = QtGui.QWidget()
        self.page_tree.setObjectName("page_tree")
        self.gridLayout_2 = QtGui.QGridLayout(self.page_tree)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeView = QtGui.QTreeView(self.page_tree)
        self.treeView.setObjectName("treeView")
        self.gridLayout_2.addWidget(self.treeView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_tree)
        self.page_table = QtGui.QWidget()
        self.page_table.setObjectName("page_table")
        self.gridLayout = QtGui.QGridLayout(self.page_table)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtGui.QTableView(self.page_table)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_table)
        self.splitter_left_right = QtGui.QSplitter(self.splitter_top_bottom)
        self.splitter_left_right.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_left_right.setObjectName("splitter_left_right")
        self.layoutWidget = QtGui.QWidget(self.splitter_left_right)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_5.addWidget(self.textEdit)
        self.widget = QtGui.QWidget(self.splitter_left_right)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(277, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_add_from_text_file = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_add_from_text_file.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_add_from_text_file.setObjectName("pushButton_add_from_text_file")
        self.gridLayout_4.addWidget(self.pushButton_add_from_text_file, 0, 0, 1, 1)
        self.pushButton_add_from_database = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_add_from_database.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_add_from_database.setObjectName("pushButton_add_from_database")
        self.gridLayout_4.addWidget(self.pushButton_add_from_database, 0, 1, 1, 1)
        self.pushButton_add_from_GUI_selector = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_add_from_GUI_selector.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_add_from_GUI_selector.setObjectName("pushButton_add_from_GUI_selector")
        self.gridLayout_4.addWidget(self.pushButton_add_from_GUI_selector, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setMinimumSize(QtCore.QSize(249, 57))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_group_based = QtGui.QRadioButton(self.groupBox)
        self.radioButton_group_based.setMinimumSize(QtCore.QSize(104, 20))
        self.radioButton_group_based.setObjectName("radioButton_group_based")
        self.gridLayout_3.addWidget(self.radioButton_group_based, 0, 0, 1, 1)
        self.radioButton_channel_based = QtGui.QRadioButton(self.groupBox)
        self.radioButton_channel_based.setMinimumSize(QtCore.QSize(117, 20))
        self.radioButton_channel_based.setChecked(True)
        self.radioButton_channel_based.setObjectName("radioButton_channel_based")
        self.gridLayout_3.addWidget(self.radioButton_channel_based, 0, 1, 1, 1)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_config_name = QtGui.QLineEdit(self.widget)
        self.lineEdit_config_name.setObjectName("lineEdit_config_name")
        self.horizontalLayout_3.addWidget(self.lineEdit_config_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.checkBox_save_config_to_file = QtGui.QCheckBox(self.widget)
        self.checkBox_save_config_to_file.setObjectName("checkBox_save_config_to_file")
        self.horizontalLayout_4.addWidget(self.checkBox_save_config_to_file)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_preferences = QtGui.QPushButton(self.widget)
        self.pushButton_preferences.setObjectName("pushButton_preferences")
        self.horizontalLayout_2.addWidget(self.pushButton_preferences)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_5.addWidget(self.splitter_top_bottom, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Setup Dialog for Tuner Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Add from", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_from_text_file.setText(QtGui.QApplication.translate("Dialog", "Text File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_from_database.setText(QtGui.QApplication.translate("Dialog", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_from_GUI_selector.setText(QtGui.QApplication.translate("Dialog", "GUI Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_group_based.setText(QtGui.QApplication.translate("Dialog", "Group-based", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_channel_based.setText(QtGui.QApplication.translate("Dialog", "Channel-based", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Config Name", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_save_config_to_file.setText(QtGui.QApplication.translate("Dialog", "Save config to file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_preferences.setText(QtGui.QApplication.translate("Dialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))

