# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tunerConfigSetupDialog.ui'
#
# Created: Tue Nov 20 21:43:20 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(843, 605)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_top_bottom = QtGui.QSplitter(Dialog)
        self.splitter_top_bottom.setOrientation(QtCore.Qt.Vertical)
        self.splitter_top_bottom.setObjectName("splitter_top_bottom")
        self.treeView = QtGui.QTreeView(self.splitter_top_bottom)
        self.treeView.setObjectName("treeView")
        self.splitter_left_right = QtGui.QSplitter(self.splitter_top_bottom)
        self.splitter_left_right.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_left_right.setObjectName("splitter_left_right")
        self.layoutWidget = QtGui.QWidget(self.splitter_left_right)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_5.addWidget(self.textEdit)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_left_right)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_add_from_database = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_add_from_database.setObjectName("pushButton_add_from_database")
        self.horizontalLayout.addWidget(self.pushButton_add_from_database)
        self.pushButton_add_from_GUI_selector = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_add_from_GUI_selector.setObjectName("pushButton_add_from_GUI_selector")
        self.horizontalLayout.addWidget(self.pushButton_add_from_GUI_selector)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_config_name = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_config_name.setObjectName("lineEdit_config_name")
        self.horizontalLayout_3.addWidget(self.lineEdit_config_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.checkBox_save_config_to_file = QtGui.QCheckBox(self.layoutWidget1)
        self.checkBox_save_config_to_file.setObjectName("checkBox_save_config_to_file")
        self.horizontalLayout_4.addWidget(self.checkBox_save_config_to_file)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_preferences = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_preferences.setObjectName("pushButton_preferences")
        self.horizontalLayout_2.addWidget(self.pushButton_preferences)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget1)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.splitter_top_bottom, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Setup Dialog for Tuner Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_from_database.setText(QtGui.QApplication.translate("Dialog", "Add from database...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_from_GUI_selector.setText(QtGui.QApplication.translate("Dialog", "Add from GUI Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Config Name", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_save_config_to_file.setText(QtGui.QApplication.translate("Dialog", "Save config to file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_preferences.setText(QtGui.QApplication.translate("Dialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))

