# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_channel_explorer.ui'
#
# Created: Wed Oct  3 19:26:09 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(926, 737)
        Dialog.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_2 = QtGui.QSplitter(Dialog)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widget = QtGui.QWidget(self.splitter_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.groupBox_filter_mode = QtGui.QGroupBox(self.widget)
        self.groupBox_filter_mode.setAutoFillBackground(False)
        self.groupBox_filter_mode.setStyleSheet(_fromUtf8("border: 2px solid black;\n"
"padding: 3px;"))
        self.groupBox_filter_mode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_filter_mode.setFlat(False)
        self.groupBox_filter_mode.setObjectName(_fromUtf8("groupBox_filter_mode"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_filter_mode)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_simple = QtGui.QRadioButton(self.groupBox_filter_mode)
        self.radioButton_simple.setStyleSheet(_fromUtf8("border: transparent;"))
        self.radioButton_simple.setChecked(True)
        self.radioButton_simple.setObjectName(_fromUtf8("radioButton_simple"))
        self.horizontalLayout.addWidget(self.radioButton_simple)
        self.radioButton_advanced = QtGui.QRadioButton(self.groupBox_filter_mode)
        self.radioButton_advanced.setStyleSheet(_fromUtf8("border: transparent;"))
        self.radioButton_advanced.setObjectName(_fromUtf8("radioButton_advanced"))
        self.horizontalLayout.addWidget(self.radioButton_advanced)
        self.horizontalLayout_5.addWidget(self.groupBox_filter_mode)
        self.checkBox_filter_case_sensitive = QtGui.QCheckBox(self.widget)
        self.checkBox_filter_case_sensitive.setMaximumSize(QtCore.QSize(16777215, 21))
        self.checkBox_filter_case_sensitive.setObjectName(_fromUtf8("checkBox_filter_case_sensitive"))
        self.horizontalLayout_5.addWidget(self.checkBox_filter_case_sensitive)
        self.groupBox_elements_or_channels = QtGui.QGroupBox(self.widget)
        self.groupBox_elements_or_channels.setAutoFillBackground(False)
        self.groupBox_elements_or_channels.setStyleSheet(_fromUtf8("   border: 2px solid black;\n"
"   padding: 3px;\n"
""))
        self.groupBox_elements_or_channels.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox_elements_or_channels.setObjectName(_fromUtf8("groupBox_elements_or_channels"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_elements_or_channels)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioButton_elements = QtGui.QRadioButton(self.groupBox_elements_or_channels)
        self.radioButton_elements.setStyleSheet(_fromUtf8("border: transparent;"))
        self.radioButton_elements.setChecked(True)
        self.radioButton_elements.setObjectName(_fromUtf8("radioButton_elements"))
        self.gridLayout.addWidget(self.radioButton_elements, 0, 0, 1, 1)
        self.radioButton_channels = QtGui.QRadioButton(self.groupBox_elements_or_channels)
        self.radioButton_channels.setStyleSheet(_fromUtf8("border: transparent;"))
        self.radioButton_channels.setObjectName(_fromUtf8("radioButton_channels"))
        self.gridLayout.addWidget(self.radioButton_channels, 0, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_elements_or_channels)
        spacerItem = QtGui.QSpacerItem(16777215, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton_search = QtGui.QPushButton(self.widget)
        self.pushButton_search.setMaximumSize(QtCore.QSize(16777215, 27))
        self.pushButton_search.setObjectName(_fromUtf8("pushButton_search"))
        self.horizontalLayout_5.addWidget(self.pushButton_search)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.stackedWidget = QtGui.QStackedWidget(self.widget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_advanced = QtGui.QWidget()
        self.page_advanced.setObjectName(_fromUtf8("page_advanced"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_advanced)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_add_row = QtGui.QPushButton(self.page_advanced)
        self.pushButton_add_row.setMaximumSize(QtCore.QSize(16777215, 27))
        self.pushButton_add_row.setObjectName(_fromUtf8("pushButton_add_row"))
        self.horizontalLayout_2.addWidget(self.pushButton_add_row)
        self.pushButton_remove_row = QtGui.QPushButton(self.page_advanced)
        self.pushButton_remove_row.setMaximumSize(QtCore.QSize(16777215, 27))
        self.pushButton_remove_row.setObjectName(_fromUtf8("pushButton_remove_row"))
        self.horizontalLayout_2.addWidget(self.pushButton_remove_row)
        spacerItem1 = QtGui.QSpacerItem(16777215, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget_filter = QtGui.QTableWidget(self.page_advanced)
        self.tableWidget_filter.setObjectName(_fromUtf8("tableWidget_filter"))
        self.tableWidget_filter.setColumnCount(11)
        self.tableWidget_filter.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_filter.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_filter.setItem(0, 1, item)
        self.tableWidget_filter.horizontalHeader().setMinimumSectionSize(16)
        self.tableWidget_filter.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget_filter)
        self.stackedWidget.addWidget(self.page_advanced)
        self.page_simple = QtGui.QWidget()
        self.page_simple.setObjectName(_fromUtf8("page_simple"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_simple)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_7 = QtGui.QLabel(self.page_simple)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.checkBox_simple_NOT = QtGui.QCheckBox(self.page_simple)
        self.checkBox_simple_NOT.setText(_fromUtf8(""))
        self.checkBox_simple_NOT.setObjectName(_fromUtf8("checkBox_simple_NOT"))
        self.verticalLayout_8.addWidget(self.checkBox_simple_NOT)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.page_simple)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.comboBox_simple_property = QtGui.QComboBox(self.page_simple)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_simple_property.sizePolicy().hasHeightForWidth())
        self.comboBox_simple_property.setSizePolicy(sizePolicy)
        self.comboBox_simple_property.setObjectName(_fromUtf8("comboBox_simple_property"))
        self.verticalLayout_4.addWidget(self.comboBox_simple_property)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(self.page_simple)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.comboBox_simple_operator = QtGui.QComboBox(self.page_simple)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_simple_operator.sizePolicy().hasHeightForWidth())
        self.comboBox_simple_operator.setSizePolicy(sizePolicy)
        self.comboBox_simple_operator.setObjectName(_fromUtf8("comboBox_simple_operator"))
        self.verticalLayout_5.addWidget(self.comboBox_simple_operator)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_5 = QtGui.QLabel(self.page_simple)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.comboBox_simple_index = QtGui.QComboBox(self.page_simple)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_simple_index.sizePolicy().hasHeightForWidth())
        self.comboBox_simple_index.setSizePolicy(sizePolicy)
        self.comboBox_simple_index.setObjectName(_fromUtf8("comboBox_simple_index"))
        self.verticalLayout_6.addWidget(self.comboBox_simple_index)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_6 = QtGui.QLabel(self.page_simple)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_7.addWidget(self.label_6)
        self.comboBox_simple_value = QtGui.QComboBox(self.page_simple)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_simple_value.sizePolicy().hasHeightForWidth())
        self.comboBox_simple_value.setSizePolicy(sizePolicy)
        self.comboBox_simple_value.setEditable(True)
        self.comboBox_simple_value.setObjectName(_fromUtf8("comboBox_simple_value"))
        self.verticalLayout_7.addWidget(self.comboBox_simple_value)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtGui.QSpacerItem(20, 300, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page_simple)
        self.verticalLayout_9.addWidget(self.stackedWidget)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_nMatched_nSelected = QtGui.QLabel(self.layoutWidget)
        self.label_nMatched_nSelected.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_nMatched_nSelected.setObjectName(_fromUtf8("label_nMatched_nSelected"))
        self.verticalLayout_3.addWidget(self.label_nMatched_nSelected)
        self.tableWidget_matched = QtGui.QTableWidget(self.layoutWidget)
        self.tableWidget_matched.setObjectName(_fromUtf8("tableWidget_matched"))
        self.tableWidget_matched.setColumnCount(15)
        self.tableWidget_matched.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(14, item)
        self.verticalLayout_3.addWidget(self.tableWidget_matched)
        self.widget1 = QtGui.QWidget(self.splitter)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox_choice_list = QtGui.QComboBox(self.widget1)
        self.comboBox_choice_list.setObjectName(_fromUtf8("comboBox_choice_list"))
        self.horizontalLayout_3.addWidget(self.comboBox_choice_list)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listView_choice_list = QtGui.QListView(self.widget1)
        self.listView_choice_list.setObjectName(_fromUtf8("listView_choice_list"))
        self.verticalLayout_2.addWidget(self.listView_choice_list)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Channel/Element Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_filter_mode.setTitle(QtGui.QApplication.translate("Dialog", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_simple.setText(QtGui.QApplication.translate("Dialog", "Simple", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_advanced.setText(QtGui.QApplication.translate("Dialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_filter_case_sensitive.setText(QtGui.QApplication.translate("Dialog", "Case-sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_elements_or_channels.setTitle(QtGui.QApplication.translate("Dialog", "Object Type", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_elements.setText(QtGui.QApplication.translate("Dialog", "Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_channels.setText(QtGui.QApplication.translate("Dialog", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search.setText(QtGui.QApplication.translate("Dialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_row.setText(QtGui.QApplication.translate("Dialog", "Add Row", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row.setText(QtGui.QApplication.translate("Dialog", "Remove Row", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Filter Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Filter Set 1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "AND/OR", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "Filter Set 2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog", "NOT", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog", "Property", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog", "Operator", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("Dialog", "Index", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("Dialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_filter.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("Dialog", "Expression", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_filter.isSortingEnabled()
        self.tableWidget_filter.setSortingEnabled(False)
        self.tableWidget_filter.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "NOT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Operator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nMatched_nSelected.setText(QtGui.QApplication.translate("Dialog", "Matched Objects (0 matched, 0 selected)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog", "Dev. Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog", "Cell", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog", "Family", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog", "Girder", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog", "Group", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog", "Lat. Index", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog", "Eff. Len.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("Dialog", "Phys. Len.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("Dialog", "PV", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("Dialog", "sb", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("Dialog", "se", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(12)
        item.setText(QtGui.QApplication.translate("Dialog", "Symmetry", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(13)
        item.setText(QtGui.QApplication.translate("Dialog", "Virtual", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidget_matched.horizontalHeaderItem(14)
        item.setText(QtGui.QApplication.translate("Dialog", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Choice List", None, QtGui.QApplication.UnicodeUTF8))

