# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_channel_explorer_startup_set_dialog.ui'
#
# Created: Wed Nov 14 16:08:55 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(678, 497)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtGui.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.listWidget_group = QtGui.QListWidget(self.splitter)
        self.listWidget_group.setObjectName("listWidget_group")
        QtGui.QListWidgetItem(self.listWidget_group)
        QtGui.QListWidgetItem(self.listWidget_group)
        self.stackedWidget = QtGui.QStackedWidget(self.splitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_misc = QtGui.QWidget()
        self.page_misc.setObjectName("page_misc")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_misc)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.page_misc)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.page_misc)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.page_misc)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.page_misc)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.page_misc)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_filter_mode = QtGui.QComboBox(self.page_misc)
        self.comboBox_filter_mode.setObjectName("comboBox_filter_mode")
        self.comboBox_filter_mode.addItem("")
        self.comboBox_filter_mode.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_filter_mode)
        self.comboBox_case_sensitivity = QtGui.QComboBox(self.page_misc)
        self.comboBox_case_sensitivity.setObjectName("comboBox_case_sensitivity")
        self.comboBox_case_sensitivity.addItem("")
        self.comboBox_case_sensitivity.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_case_sensitivity)
        self.comboBox_column_sorting = QtGui.QComboBox(self.page_misc)
        self.comboBox_column_sorting.setObjectName("comboBox_column_sorting")
        self.comboBox_column_sorting.addItem("")
        self.comboBox_column_sorting.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_column_sorting)
        self.comboBox_machine = QtGui.QComboBox(self.page_misc)
        self.comboBox_machine.setObjectName("comboBox_machine")
        self.comboBox_machine.addItem("")
        self.comboBox_machine.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_machine)
        self.lineEdit_lattice_name = QtGui.QLineEdit(self.page_misc)
        self.lineEdit_lattice_name.setObjectName("lineEdit_lattice_name")
        self.verticalLayout_2.addWidget(self.lineEdit_lattice_name)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtGui.QSpacerItem(20, 281, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page_misc)
        self.page_column_visibility_order = QtGui.QWidget()
        self.page_column_visibility_order.setObjectName("page_column_visibility_order")
        self.stackedWidget.addWidget(self.page_column_visibility_order)
        self.verticalLayout_4.addWidget(self.splitter)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_restore_default = QtGui.QPushButton(Dialog)
        self.pushButton_restore_default.setObjectName("pushButton_restore_default")
        self.horizontalLayout_7.addWidget(self.pushButton_restore_default)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_7.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Startup Settings", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget_group.isSortingEnabled()
        self.listWidget_group.setSortingEnabled(False)
        self.listWidget_group.item(0).setText(QtGui.QApplication.translate("Dialog", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_group.item(1).setText(QtGui.QApplication.translate("Dialog", "Miscellaneous", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_group.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtGui.QApplication.translate("Dialog", "Filter Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Case-Sensitivity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Column Sorting:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Machine:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Lattice Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_filter_mode.setItemText(0, QtGui.QApplication.translate("Dialog", "Simple", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_filter_mode.setItemText(1, QtGui.QApplication.translate("Dialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_case_sensitivity.setItemText(0, QtGui.QApplication.translate("Dialog", "sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_case_sensitivity.setItemText(1, QtGui.QApplication.translate("Dialog", "insensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_column_sorting.setItemText(0, QtGui.QApplication.translate("Dialog", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_column_sorting.setItemText(1, QtGui.QApplication.translate("Dialog", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_machine.setItemText(0, QtGui.QApplication.translate("Dialog", "NSLS2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_machine.setItemText(1, QtGui.QApplication.translate("Dialog", "NSLS2V2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_restore_default.setText(QtGui.QApplication.translate("Dialog", "Restore Default", None, QtGui.QApplication.UnicodeUTF8))

