# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_lattice_tuner_for_reference.ui'
#
# Created: Fri Oct  5 19:12:31 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1015, 766)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave = QtGui.QMenu(self.menuFile)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuLoad = QtGui.QMenu(self.menuFile)
        self.menuLoad.setObjectName(_fromUtf8("menuLoad"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_example = QtGui.QDockWidget(MainWindow)
        self.dockWidget_example.setObjectName(_fromUtf8("dockWidget_example"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.dockWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeView = QtGui.QTreeView(self.splitter)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.tabWidget_mode = QtGui.QTabWidget(self.splitter)
        self.tabWidget_mode.setObjectName(_fromUtf8("tabWidget_mode"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_step_up = QtGui.QPushButton(self.tab)
        self.pushButton_step_up.setObjectName(_fromUtf8("pushButton_step_up"))
        self.horizontalLayout.addWidget(self.pushButton_step_up)
        self.pushButton_step_down = QtGui.QPushButton(self.tab)
        self.pushButton_step_down.setObjectName(_fromUtf8("pushButton_step_down"))
        self.horizontalLayout.addWidget(self.pushButton_step_down)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_update = QtGui.QPushButton(self.tab)
        self.pushButton_update.setObjectName(_fromUtf8("pushButton_update"))
        self.horizontalLayout_2.addWidget(self.pushButton_update)
        self.checkBox_auto = QtGui.QCheckBox(self.tab)
        self.checkBox_auto.setMinimumSize(QtCore.QSize(141, 0))
        self.checkBox_auto.setObjectName(_fromUtf8("checkBox_auto"))
        self.horizontalLayout_2.addWidget(self.checkBox_auto)
        self.lineEdit_auto_update_interval = QtGui.QLineEdit(self.tab)
        self.lineEdit_auto_update_interval.setObjectName(_fromUtf8("lineEdit_auto_update_interval"))
        self.horizontalLayout_2.addWidget(self.lineEdit_auto_update_interval)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget_mode.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_7.addWidget(self.label_7)
        self.pushButton_copy_current_setp = QtGui.QPushButton(self.tab_2)
        self.pushButton_copy_current_setp.setObjectName(_fromUtf8("pushButton_copy_current_setp"))
        self.horizontalLayout_7.addWidget(self.pushButton_copy_current_setp)
        self.pushButton_copy_init_setp = QtGui.QPushButton(self.tab_2)
        self.pushButton_copy_init_setp.setObjectName(_fromUtf8("pushButton_copy_init_setp"))
        self.horizontalLayout_7.addWidget(self.pushButton_copy_init_setp)
        self.pushButton_copy_snapshot_setp = QtGui.QPushButton(self.tab_2)
        self.pushButton_copy_snapshot_setp.setObjectName(_fromUtf8("pushButton_copy_snapshot_setp"))
        self.horizontalLayout_7.addWidget(self.pushButton_copy_snapshot_setp)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_nSteps = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_nSteps.setObjectName(_fromUtf8("lineEdit_nSteps"))
        self.horizontalLayout_8.addWidget(self.lineEdit_nSteps)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_wait_after_each_step = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_wait_after_each_step.setObjectName(_fromUtf8("lineEdit_wait_after_each_step"))
        self.horizontalLayout_8.addWidget(self.lineEdit_wait_after_each_step)
        self.pushButton_start = QtGui.QPushButton(self.tab_2)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.horizontalLayout_8.addWidget(self.pushButton_start)
        self.pushButton_stop = QtGui.QPushButton(self.tab_2)
        self.pushButton_stop.setObjectName(_fromUtf8("pushButton_stop"))
        self.horizontalLayout_8.addWidget(self.pushButton_stop)
        self.pushButton_revert = QtGui.QPushButton(self.tab_2)
        self.pushButton_revert.setObjectName(_fromUtf8("pushButton_revert"))
        self.horizontalLayout_8.addWidget(self.pushButton_revert)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.tabWidget_mode.addTab(self.tab_2, _fromUtf8(""))
        self.tabWidget_metadata = QtGui.QTabWidget(self.splitter)
        self.tabWidget_metadata.setObjectName(_fromUtf8("tabWidget_metadata"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_config_username = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_config_username.setObjectName(_fromUtf8("lineEdit_config_username"))
        self.horizontalLayout_3.addWidget(self.lineEdit_config_username)
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_config_timestamp = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_config_timestamp.setObjectName(_fromUtf8("lineEdit_config_timestamp"))
        self.horizontalLayout_3.addWidget(self.lineEdit_config_timestamp)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.textEdit_config_description = QtGui.QTextEdit(self.tab_3)
        self.textEdit_config_description.setObjectName(_fromUtf8("textEdit_config_description"))
        self.horizontalLayout_4.addWidget(self.textEdit_config_description)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tabWidget_metadata.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_snapshot_username = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_snapshot_username.setObjectName(_fromUtf8("lineEdit_snapshot_username"))
        self.horizontalLayout_6.addWidget(self.lineEdit_snapshot_username)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit_snapshot_timestamp = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_snapshot_timestamp.setObjectName(_fromUtf8("lineEdit_snapshot_timestamp"))
        self.horizontalLayout_6.addWidget(self.lineEdit_snapshot_timestamp)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.textEdit_snapshot_description = QtGui.QTextEdit(self.tab_4)
        self.textEdit_snapshot_description.setObjectName(_fromUtf8("textEdit_snapshot_description"))
        self.horizontalLayout_5.addWidget(self.textEdit_snapshot_description)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget_metadata.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.dockWidget_example.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_example)
        self.actionNewConfig = QtGui.QAction(MainWindow)
        self.actionNewConfig.setObjectName(_fromUtf8("actionNewConfig"))
        self.actionLoadConfigFileInNewTab = QtGui.QAction(MainWindow)
        self.actionLoadConfigFileInNewTab.setObjectName(_fromUtf8("actionLoadConfigFileInNewTab"))
        self.actionLoadSnapshotFileInNewTab = QtGui.QAction(MainWindow)
        self.actionLoadSnapshotFileInNewTab.setObjectName(_fromUtf8("actionLoadSnapshotFileInNewTab"))
        self.actionLoadConfigFileInCurrentTab = QtGui.QAction(MainWindow)
        self.actionLoadConfigFileInCurrentTab.setObjectName(_fromUtf8("actionLoadConfigFileInCurrentTab"))
        self.actionLoadSnapshotFileInCurrentTab = QtGui.QAction(MainWindow)
        self.actionLoadSnapshotFileInCurrentTab.setObjectName(_fromUtf8("actionLoadSnapshotFileInCurrentTab"))
        self.actionSaveConfigFile = QtGui.QAction(MainWindow)
        self.actionSaveConfigFile.setObjectName(_fromUtf8("actionSaveConfigFile"))
        self.actionSaveSnapshotFile = QtGui.QAction(MainWindow)
        self.actionSaveSnapshotFile.setObjectName(_fromUtf8("actionSaveSnapshotFile"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName(_fromUtf8("actionTest"))
        self.actionConfig_from_file = QtGui.QAction(MainWindow)
        self.actionConfig_from_file.setObjectName(_fromUtf8("actionConfig_from_file"))
        self.actionSnapshot_from_file = QtGui.QAction(MainWindow)
        self.actionSnapshot_from_file.setObjectName(_fromUtf8("actionSnapshot_from_file"))
        self.actionGrouped = QtGui.QAction(MainWindow)
        self.actionGrouped.setObjectName(_fromUtf8("actionGrouped"))
        self.actionUngrouped = QtGui.QAction(MainWindow)
        self.actionUngrouped.setObjectName(_fromUtf8("actionUngrouped"))
        self.actionConfig_Metadata = QtGui.QAction(MainWindow)
        self.actionConfig_Metadata.setObjectName(_fromUtf8("actionConfig_Metadata"))
        self.actionSnapshot_Metadata = QtGui.QAction(MainWindow)
        self.actionSnapshot_Metadata.setObjectName(_fromUtf8("actionSnapshot_Metadata"))
        self.actionDefault_config_columns = QtGui.QAction(MainWindow)
        self.actionDefault_config_columns.setObjectName(_fromUtf8("actionDefault_config_columns"))
        self.actionDefault_snapshot_columns = QtGui.QAction(MainWindow)
        self.actionDefault_snapshot_columns.setObjectName(_fromUtf8("actionDefault_snapshot_columns"))
        self.actionUser_defined_config_columns = QtGui.QAction(MainWindow)
        self.actionUser_defined_config_columns.setObjectName(_fromUtf8("actionUser_defined_config_columns"))
        self.actionUser_defined_snapshot_columns = QtGui.QAction(MainWindow)
        self.actionUser_defined_snapshot_columns.setObjectName(_fromUtf8("actionUser_defined_snapshot_columns"))
        self.menuSave.addAction(self.actionSaveConfigFile)
        self.menuSave.addAction(self.actionSaveSnapshotFile)
        self.menuLoad.addAction(self.actionConfig_from_file)
        self.menuLoad.addAction(self.actionSnapshot_from_file)
        self.menuFile.addAction(self.actionNewConfig)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menu_View.addAction(self.actionGrouped)
        self.menu_View.addAction(self.actionUngrouped)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.actionConfig_Metadata)
        self.menu_View.addAction(self.actionSnapshot_Metadata)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.actionDefault_config_columns)
        self.menu_View.addAction(self.actionDefault_snapshot_columns)
        self.menu_View.addAction(self.actionUser_defined_config_columns)
        self.menu_View.addAction(self.actionUser_defined_snapshot_columns)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_mode.setCurrentIndex(0)
        self.tabWidget_metadata.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Lattice Tuner", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad.setTitle(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_step_up.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_step_down.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_update.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_auto.setText(QtGui.QApplication.translate("MainWindow", "Auto: Interval [s]", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_mode.setTabText(self.tabWidget_mode.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Step Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Copy into target set points:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_copy_current_setp.setText(QtGui.QApplication.translate("MainWindow", "Current Setpoints", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_copy_init_setp.setText(QtGui.QApplication.translate("MainWindow", "Init. Setpoints", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_copy_snapshot_setp.setText(QtGui.QApplication.translate("MainWindow", "Snapshot Setpoints", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Number of Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Wait after Each Step [s]:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_revert.setText(QtGui.QApplication.translate("MainWindow", "Revert", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_mode.setTabText(self.tabWidget_mode.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Ramp Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Created by", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Created on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_metadata.setTabText(self.tabWidget_metadata.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Config Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Created by", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Created on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_metadata.setTabText(self.tabWidget_metadata.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Snapshot Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewConfig.setText(QtGui.QApplication.translate("MainWindow", "&New Config...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewConfig.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadConfigFileInNewTab.setText(QtGui.QApplication.translate("MainWindow", "Config file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSnapshotFileInNewTab.setText(QtGui.QApplication.translate("MainWindow", "Snapshot file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadConfigFileInCurrentTab.setText(QtGui.QApplication.translate("MainWindow", "Config file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSnapshotFileInCurrentTab.setText(QtGui.QApplication.translate("MainWindow", "Snapshot file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveConfigFile.setText(QtGui.QApplication.translate("MainWindow", "Config to file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSnapshotFile.setText(QtGui.QApplication.translate("MainWindow", "Snapshot to file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "Load Snapshot File...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfig_from_file.setText(QtGui.QApplication.translate("MainWindow", "Config from file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSnapshot_from_file.setText(QtGui.QApplication.translate("MainWindow", "Snapshot from file...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGrouped.setText(QtGui.QApplication.translate("MainWindow", "&Grouped", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUngrouped.setText(QtGui.QApplication.translate("MainWindow", "&Ungrouped", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfig_Metadata.setText(QtGui.QApplication.translate("MainWindow", "Config Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSnapshot_Metadata.setText(QtGui.QApplication.translate("MainWindow", "Snapshot Metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefault_config_columns.setText(QtGui.QApplication.translate("MainWindow", "Default config columns", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefault_snapshot_columns.setText(QtGui.QApplication.translate("MainWindow", "Default snapshot columns", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUser_defined_config_columns.setText(QtGui.QApplication.translate("MainWindow", "User-defined config columns", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUser_defined_snapshot_columns.setText(QtGui.QApplication.translate("MainWindow", "User-defined snapshot columns", None, QtGui.QApplication.UnicodeUTF8))

