#! /usr/bin/env python

"""

Qt4 Designer File Module

This module contains all the .ui files generated by Qt 4 Designer,
as well as the python files converted from the .ui files with the
pyuic4 command.

"""