# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_element_selector.ui'
#
# Created: Tue Oct 18 18:40:14 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(926, 737)
        Dialog.setModal(True)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 27))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.checkBox_filter_case_sensitive = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_filter_case_sensitive.setMaximumSize(QtCore.QSize(16777215, 21))
        self.checkBox_filter_case_sensitive.setObjectName(_fromUtf8("checkBox_filter_case_sensitive"))
        self.horizontalLayout.addWidget(self.checkBox_filter_case_sensitive)
        spacerItem = QtGui.QSpacerItem(16777215, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_add_row = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_add_row.setMaximumSize(QtCore.QSize(16777215, 27))
        self.pushButton_add_row.setObjectName(_fromUtf8("pushButton_add_row"))
        self.horizontalLayout.addWidget(self.pushButton_add_row)
        self.pushButton_remove_row = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_remove_row.setMaximumSize(QtCore.QSize(16777215, 27))
        self.pushButton_remove_row.setObjectName(_fromUtf8("pushButton_remove_row"))
        self.horizontalLayout.addWidget(self.pushButton_remove_row)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget_filter = QtGui.QTableWidget(self.layoutWidget)
        self.tableWidget_filter.setObjectName(_fromUtf8("tableWidget_filter"))
        self.tableWidget_filter.setColumnCount(16)
        self.tableWidget_filter.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_filter.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tableWidget_filter.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_filter.setItem(0, 1, item)
        self.tableWidget_filter.horizontalHeader().setMinimumSectionSize(16)
        self.tableWidget_filter.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget_filter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 31))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.tableWidget_choice_list = QtGui.QTableWidget(self.layoutWidget1)
        self.tableWidget_choice_list.setObjectName(_fromUtf8("tableWidget_choice_list"))
        self.tableWidget_choice_list.setColumnCount(15)
        self.tableWidget_choice_list.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_choice_list.setHorizontalHeaderItem(14, item)
        self.verticalLayout_2.addWidget(self.tableWidget_choice_list)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_nMatched_nSelected = QtGui.QLabel(self.layoutWidget2)
        self.label_nMatched_nSelected.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_nMatched_nSelected.setObjectName(_fromUtf8("label_nMatched_nSelected"))
        self.verticalLayout_3.addWidget(self.label_nMatched_nSelected)
        self.tableWidget_matched = QtGui.QTableWidget(self.layoutWidget2)
        self.tableWidget_matched.setObjectName(_fromUtf8("tableWidget_matched"))
        self.tableWidget_matched.setColumnCount(15)
        self.tableWidget_matched.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_matched.setHorizontalHeaderItem(14, item)
        self.verticalLayout_3.addWidget(self.tableWidget_matched)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Element Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_filter_case_sensitive.setText(QtGui.QApplication.translate("Dialog", "Case-sensitive", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_row.setText(QtGui.QApplication.translate("Dialog", "Add Row", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_row.setText(QtGui.QApplication.translate("Dialog", "Remove Row", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Excl.", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Dev. Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Family", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "Girder", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Lat. Index", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "Eff. Len.", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("Dialog", "Phys. Len.", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("Dialog", "PV", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("Dialog", "sb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("Dialog", "se", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("Dialog", "Symmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("Dialog", "Virtual", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_filter.horizontalHeaderItem(15).setText(QtGui.QApplication.translate("Dialog", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_filter.isSortingEnabled()
        self.tableWidget_filter.setSortingEnabled(False)
        self.tableWidget_filter.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "HLA Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setPlainText(QtGui.QApplication.translate("Dialog", "hla.getElements(*)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Choice List", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Dev. Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Family", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Girder", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "Lat. Index", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Eff. Len.", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "Phys. Len.", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("Dialog", "PV", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("Dialog", "sb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("Dialog", "se", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("Dialog", "Symmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("Dialog", "Virtual", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_choice_list.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("Dialog", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nMatched_nSelected.setText(QtGui.QApplication.translate("Dialog", "Matched Elements (0 matched, 0 selected)", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Dev. Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Cell", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Family", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Girder", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "Lat. Index", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Eff. Len.", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "Phys. Len.", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("Dialog", "PV", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("Dialog", "sb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("Dialog", "se", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("Dialog", "Symmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("Dialog", "Virtual", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_matched.horizontalHeaderItem(14).setText(QtGui.QApplication.translate("Dialog", "Sequence", None, QtGui.QApplication.UnicodeUTF8))

