# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_addNewCurveForCurvesDockWidget.ui'
#
# Created: Wed Mar 21 11:32:38 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(667, 483)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter = QtGui.QSplitter(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_dispName = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_dispName.setObjectName(_fromUtf8("lineEdit_dispName"))
        self.horizontalLayout.addWidget(self.lineEdit_dispName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.checkBox_visible = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_visible.setText(_fromUtf8(""))
        self.checkBox_visible.setChecked(True)
        self.checkBox_visible.setObjectName(_fromUtf8("checkBox_visible"))
        self.horizontalLayout_2.addWidget(self.checkBox_visible)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox_figName = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_figName.setEditable(True)
        self.comboBox_figName.setObjectName(_fromUtf8("comboBox_figName"))
        self.horizontalLayout_3.addWidget(self.comboBox_figName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_4.addWidget(self.label_16)
        self.spinBox_canvasRowCount = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_canvasRowCount.setMinimum(1)
        self.spinBox_canvasRowCount.setMaximum(10)
        self.spinBox_canvasRowCount.setObjectName(_fromUtf8("spinBox_canvasRowCount"))
        self.horizontalLayout_4.addWidget(self.spinBox_canvasRowCount)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_5.addWidget(self.label_17)
        self.spinBox_canvasColCount = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_canvasColCount.setMinimum(1)
        self.spinBox_canvasColCount.setMaximum(10)
        self.spinBox_canvasColCount.setObjectName(_fromUtf8("spinBox_canvasColCount"))
        self.horizontalLayout_5.addWidget(self.spinBox_canvasColCount)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.listWidget_canvasRowPos = QtGui.QListWidget(self.layoutWidget)
        self.listWidget_canvasRowPos.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.listWidget_canvasRowPos.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget_canvasRowPos.setObjectName(_fromUtf8("listWidget_canvasRowPos"))
        self.horizontalLayout_6.addWidget(self.listWidget_canvasRowPos)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_7.addWidget(self.label_18)
        self.listWidget_canvasColPos = QtGui.QListWidget(self.layoutWidget)
        self.listWidget_canvasColPos.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.listWidget_canvasColPos.setObjectName(_fromUtf8("listWidget_canvasColPos"))
        self.horizontalLayout_7.addWidget(self.listWidget_canvasColPos)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_xVarName = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_xVarName.setObjectName(_fromUtf8("comboBox_xVarName"))
        self.gridLayout_2.addWidget(self.comboBox_xVarName, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.comboBox_xAxis = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_xAxis.setObjectName(_fromUtf8("comboBox_xAxis"))
        self.gridLayout_2.addWidget(self.comboBox_xAxis, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.comboBox_yVarName = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_yVarName.setObjectName(_fromUtf8("comboBox_yVarName"))
        self.gridLayout_2.addWidget(self.comboBox_yVarName, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.comboBox_yAxis = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_yAxis.setObjectName(_fromUtf8("comboBox_yAxis"))
        self.gridLayout_2.addWidget(self.comboBox_yAxis, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.comboBox_lineColor = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_lineColor.setObjectName(_fromUtf8("comboBox_lineColor"))
        self.gridLayout.addWidget(self.comboBox_lineColor, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.comboBox_lineStyle = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_lineStyle.setObjectName(_fromUtf8("comboBox_lineStyle"))
        self.gridLayout.addWidget(self.comboBox_lineStyle, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.comboBox_lineWidth = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_lineWidth.setObjectName(_fromUtf8("comboBox_lineWidth"))
        self.gridLayout.addWidget(self.comboBox_lineWidth, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.comboBox_marker = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_marker.setObjectName(_fromUtf8("comboBox_marker"))
        self.gridLayout.addWidget(self.comboBox_marker, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.comboBox_markerSize = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_markerSize.setObjectName(_fromUtf8("comboBox_markerSize"))
        self.gridLayout.addWidget(self.comboBox_markerSize, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 5, 0, 1, 1)
        self.comboBox_markerEdgeColor = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_markerEdgeColor.setObjectName(_fromUtf8("comboBox_markerEdgeColor"))
        self.gridLayout.addWidget(self.comboBox_markerEdgeColor, 5, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.comboBox_markerFaceColor = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_markerFaceColor.setObjectName(_fromUtf8("comboBox_markerFaceColor"))
        self.gridLayout.addWidget(self.comboBox_markerFaceColor, 6, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.listWidget_canvasRowPos.setCurrentRow(-1)
        self.listWidget_canvasColPos.setCurrentRow(-1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Add a New Curve", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Display Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Visible:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Figure (Tab) Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "No. of Canvas Rows:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog", "No. of Canvas Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Canvas Row Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog", "Canvas Column Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "X Variable:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "X-Axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Y Variable:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Y-Axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Line Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Line Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Line Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Marker:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Marker Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Marker Edge Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Marker Face Color:", None, QtGui.QApplication.UnicodeUTF8))

