# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_plotter.ui'
#
# Created: Fri Mar 23 17:34:51 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(828, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_datasets = QtGui.QDockWidget(MainWindow)
        self.dockWidget_datasets.setMinimumSize(QtCore.QSize(0, 0))
        self.dockWidget_datasets.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_datasets.setObjectName(_fromUtf8("dockWidget_datasets"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.dockWidget_datasets.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_datasets)
        self.dockWidget_expression_editor = QtGui.QDockWidget(MainWindow)
        self.dockWidget_expression_editor.setMinimumSize(QtCore.QSize(179, 154))
        self.dockWidget_expression_editor.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_expression_editor.setObjectName(_fromUtf8("dockWidget_expression_editor"))
        self.dockWidgetContents_8 = QtGui.QWidget()
        self.dockWidgetContents_8.setObjectName(_fromUtf8("dockWidgetContents_8"))
        self.dockWidget_expression_editor.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_expression_editor)
        self.dockWidget_canvas_settings = QtGui.QDockWidget(MainWindow)
        self.dockWidget_canvas_settings.setMinimumSize(QtCore.QSize(161, 187))
        self.dockWidget_canvas_settings.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_canvas_settings.setObjectName(_fromUtf8("dockWidget_canvas_settings"))
        self.dockWidgetContents_9 = QtGui.QWidget()
        self.dockWidgetContents_9.setObjectName(_fromUtf8("dockWidgetContents_9"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_9)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents_9)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents_9)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem = QtGui.QSpacerItem(25, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_9)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtGui.QLineEdit(self.dockWidgetContents_9)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tableWidget_canvas_settings = QtGui.QTableWidget(self.dockWidgetContents_9)
        self.tableWidget_canvas_settings.setObjectName(_fromUtf8("tableWidget_canvas_settings"))
        self.tableWidget_canvas_settings.setColumnCount(9)
        self.tableWidget_canvas_settings.setRowCount(7)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_canvas_settings.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_canvas_settings.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget_canvas_settings.setItem(6, 0, item)
        self.gridLayout_2.addWidget(self.tableWidget_canvas_settings, 2, 0, 1, 1)
        self.dockWidget_canvas_settings.setWidget(self.dockWidgetContents_9)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_canvas_settings)
        self.dockWidget_curves = QtGui.QDockWidget(MainWindow)
        self.dockWidget_curves.setMinimumSize(QtCore.QSize(184, 150))
        self.dockWidget_curves.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_curves.setObjectName(_fromUtf8("dockWidget_curves"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.dockWidget_curves.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_curves)
        self.dockWidget_line_cursors = QtGui.QDockWidget(MainWindow)
        self.dockWidget_line_cursors.setMinimumSize(QtCore.QSize(96, 121))
        self.dockWidget_line_cursors.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget_line_cursors.setObjectName(_fromUtf8("dockWidget_line_cursors"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tableWidget_3 = QtGui.QTableWidget(self.dockWidgetContents_3)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setItem(4, 1, item)
        self.gridLayout_6.addWidget(self.tableWidget_3, 0, 0, 1, 1)
        self.dockWidget_line_cursors.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_line_cursors)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "APHLA Plotter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_datasets.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Datasets", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_expression_editor.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Expression Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_canvas_settings.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Canvas Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Fig 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Fig 2 (2,2,1)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Fig 2 (2,2,2)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Fig 2 (2,2,3)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Fig 2 (2,2,4)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Low Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "High Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Auto Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Label String", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Tick Label Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Linear/Log", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Show Tick Label", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "xBottom", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "yLeft1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "yLeft2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "yLeft3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "yLeft4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "yRight", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "yRight2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "yRight3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_canvas_settings.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "yRight4", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_canvas_settings.isSortingEnabled()
        self.tableWidget_canvas_settings.setSortingEnabled(False)
        self.tableWidget_canvas_settings.setSortingEnabled(__sortingEnabled)
        self.dockWidget_curves.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Curves", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_line_cursors.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Line Cursors", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Curve1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Curve2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Interp. Method", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Cursor1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Cursor2", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        self.tableWidget_3.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "xBottom", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.item(0, 1).setText(QtGui.QApplication.translate("MainWindow", "yLeft1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "1.4e-9", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.item(1, 1).setText(QtGui.QApplication.translate("MainWindow", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "123.45", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.item(2, 1).setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.item(3, 0).setText(QtGui.QApplication.translate("MainWindow", "56.75, 35.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.item(3, 1).setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.item(4, 0).setText(QtGui.QApplication.translate("MainWindow", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.item(4, 1).setText(QtGui.QApplication.translate("MainWindow", "nearest, ...", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)

